### ISSUE TITLE
Remove boost::filesystem as Hunter dependency

### ISSUE THREAD

**Issue by canepat** [torquem-ch/silkrpc#113]
Remove `boost::filesystem`as unused Hunter dependency

**Comment by samrath-sudesh-acharya** [comment]
@canepat  where does this boost: : filesystem exist in the repo.
I searched for it in the repo

**Comment by canepat** [comment]
@samrath-sudesh-acharya thanks for your comment! You're right, `boost::filesystem` is currently not used in the code base, but it's still present as Hunter dependency. I'm going to change the title to better track the issue. Thanks!
