### ISSUE TITLE
Explore usage of asio-grpc library

### ISSUE THREAD

**Issue by canepat** [torquem-ch/silkrpc#204]
Explore usage of [asio-grpc](https://github.com/Tradias/asio-grpc) library

This could help simplifying the code and hopefully improving the performance too

**Comment by Tradias** [comment]
Heya, I am the author of asio-grpc. Is there anything I can help you with here? Do you need any information regarding the library?

**Comment by canepat** [comment]
Hey @Tradias, thanks a lot for asking! As you can see, this issue is a reminder for a future research work using your library.

Currently we use `asio::awaitable` as C++ coroutine awaitable type and we have some code wrapping the async gRPC API into coroutines. However, such mapping occurs at the application level and just for our specific RPCs, while using asio-grpc it would happen inside the library at the infrastructure level and so we could get rid of some code not so . Moreover, your idea to wrap `asio::execution_context` around `grpc::CompletionQueue` seems really interesting to improve our threading model.

I will be back to you asking for some help when we will start working on this.

**Comment by Tradias** [comment]
Fyi, I have started to work on a pull request that shows what code simplification and correctness asio-grpc would bring.

**Comment by canepat** [comment]
> Fyi, I have started to work on a pull request that shows what code simplification and correctness asio-grpc would bring.

Thanks a lot, @Tradias! Looking forward to see your PR, please let me know if you have questions or any issue with our code.

**Comment by Tradias** [comment]
Looks like this is done now :).

**Comment by canepat** [comment]
Closed by #326
