### ISSUE TITLE
Add support for parity_listStorageKeys API

### ISSUE THREAD

**Issue by canepat** [torquem-ch/silkrpc#228]
Add support for `parity_listStorageKeys` API (see [here](https://github.com/ledgerwatch/erigon/commit/3630c264644b0ef2479ee9797902043a9133f046))

**Comment by mechanism-s** [comment]
I'm taking a look at this. A few questions:

1) For the PlainState enumeration, would a wrapper utility such as `TransactionDatabase::for_prefix` be sufficient here, or should the approach follow the Erigon code and use a dup_sort cursor (`RemoteTransaction::cursor_dup_sort`) directly?
2) What's the recommended developer workflow for trying out and end-to-end testing a SilkRPC change locally? For example, does Silkworm have something similar to Erigon's dev chain? Or, is it recommended to use Erigon directly? If so, are there any interface mismatches that may occur?

**Comment by enriavil1** [comment]
#314
