### ISSUE TITLE
Gas cost for SLOAD in debug_trace[Transaction|Call] different from RPCDaemon

### ISSUE THREAD

**Issue by Sixtysixter** [torquem-ch/silkrpc#246]
Executing the `debug_traceTransaction` cal` using the following input
```
{
  "jsonrpc":"2.0",
  "method":"debug_traceTransaction",
  "params":[
     "0x41d7ffbe4fea1aadb614c9462863fd0761de14f5d83574922c13c6cbb3bc22c1",
     {
       "disableStorage": false,
       "disableMemory": false,
       "disableStack": false
     }
  ],
  "id":1
}
```

the silkrpc result differs from the rpcdaemon one in gas cost for `SLOAD` opcode (and then the gas cost is wrong for the next opcodes).

The same difference is present in `debug_traceCall`.

**Comment by lupin012** [comment]
Fix in  https://github.com/torquem-ch/silkrpc/commit/3adeeea79a2dab7e8df158fce5783679ab6031a4
