### ISSUE TITLE
run with erigon fail

### ISSUE THREAD

**Issue by flywukong** [torquem-ch/silkrpc#345]
I have run a erigon node with privateapi==localhost:9090, in same node of silkrpcdaemon , but I failed to start silkrpcdaemon 

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/19421226/186150709-a180a3bf-c820-4e51-808b-f3cb4401100b.png">

**Comment by AndreaLanfranchi** [comment]
Actually the issue is due to incompatibility of Erigon `devel` branch with Silkrpc. Only Erigon's `stable` branch is compatible.
